Repository blues18/DEVOPS_project-Team05-, pull requests merged in 2022-12, with the labels that each got.

#4 Hotfix branches for current known Issues in Navbar navigation
  DevOps_project/src/main/java/com/dvops/maven/eclipse/product_array_object.java
  DevOps_project/src/main/webapp/includes/header.jsp
Labels: bug

#9 Product Features Merge into Develop Branches
  DevOps_project/.settings/org.eclipse.core.resources.prefs
  DevOps_project/src/main/java/UserServlet.java
  DevOps_project/src/main/java/com/dvops/maven/eclipse/User.java
  DevOps_project/src/main/java/com/dvops/maven/eclipse/registerServlet.java
  DevOps_project/src/main/webapp/WEB-INF/web.xml
  DevOps_project/src/main/webapp/images/land.JPG
  DevOps_project/src/main/webapp/images/land1.JPG
  DevOps_project/src/main/webapp/includes/header.jsp
  DevOps_project/src/main/webapp/includes/style.css
  DevOps_project/src/main/webapp/includes/table.jsp
  DevOps_project/src/main/webapp/index.jsp
  DevOps_project/src/main/webapp/login.jsp
  DevOps_project/src/main/webapp/productDetail_page.jsp
  DevOps_project/src/main/webapp/userEdit.jsp
  DevOps_project/src/main/webapp/userManagement.jsp
  DevOps_project/src/main/webapp/viewAllproduct.jsp
  README.md
Labels: documentation, enhancement

#10 Error Check: Conflicts in ProductServlet
  DevOps_project/.settings/org.eclipse.core.resources.prefs
  DevOps_project/src/main/java/UserServlet.java
  DevOps_project/src/main/java/com/dvops/maven/eclipse/ProductServlet.java
  DevOps_project/src/main/java/com/dvops/maven/eclipse/User.java
  DevOps_project/src/main/java/com/dvops/maven/eclipse/products_model.java
  DevOps_project/src/main/java/com/dvops/maven/eclipse/registerServlet.java
  DevOps_project/src/main/webapp/WEB-INF/web.xml
  DevOps_project/src/main/webapp/images/land.JPG
  DevOps_project/src/main/webapp/images/land1.JPG
  DevOps_project/src/main/webapp/includes/header.jsp
  DevOps_project/src/main/webapp/includes/style.css
  DevOps_project/src/main/webapp/includes/table.jsp
  DevOps_project/src/main/webapp/index.jsp
  DevOps_project/src/main/webapp/login.jsp
  DevOps_project/src/main/webapp/productDetail_page.jsp
  DevOps_project/src/main/webapp/userEdit.jsp
  DevOps_project/src/main/webapp/userManagement.jsp
  DevOps_project/src/main/webapp/viewAllproduct.jsp
  README.md
Labels: bug, help wanted

#15 Bugfix: edit error occur when pulling from master
  DevOps_project/src/main/java/com/dvops/maven/eclipse/User.java
  DevOps_project/src/main/java/com/dvops/maven/eclipse/UserServlet.java
  DevOps_project/src/main/java/com/dvops/maven/eclipse/registerServlet.java
  DevOps_project/src/main/webapp/WEB-INF/web.xml
  DevOps_project/src/main/webapp/includes/header.jsp
  DevOps_project/src/main/webapp/login.jsp
  DevOps_project/src/main/webapp/register_page.jsp
  DevOps_project/src/main/webapp/userEdit.jsp
  DevOps_project/src/main/webapp/userManagement.jsp
Labels: bug, help wanted
